### ISSUE TITLE
Cannot Import Game from FlashRL

### ISSUE THREAD

**Issue by JDaniel41** [UIA-CAIR/FlashRL#4]
Hello, I am looking at using FlashRL for a reinforcement learning project and I am currently trying to run the mujaffa example environment. However, when I run it, the program crashes when it tries to run `from FlashRL import Game`:

```
>>> from FlashRL import Game
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Game' from 'FlashRL' (unknown location)
```

Meanwhile, I can run `import FlashRL` just fine without any errors. Running `modules` in the python terminal does not list FlashRL, even though I was able to use `pip` to install FlashRL from this GitHub repository. Is there something I am missing? If I try running the commands as `FlashRL.Game` I still face the same issue with the following output:

```
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    FlashRL.Game("mujaffa-v1.6", fps=1, frame_callback=on_frame, grayscale=True, normalized=True)
AttributeError: module 'FlashRL' has no attribute 'Game'
```

I am pretty certain that the FlashRL module is installed, but for some reason I cannot install any of the additional files in the `lib` directory of this repository.

**Comment by JDaniel41** [comment]
For anyone facing the same issue, the solution is to use `from FlashRL.lib import Game`. This will import the `Game` module.
